  INSERT INTO ZZ_GROUPS(GROUP_ID, GROUP_NAME) 
  VALUES (1, 'USERS');
  
  INSERT INTO ZZ_GROUPS(GROUP_ID, GROUP_NAME) 
  VALUES (2, 'ADMINISTRATORS');
  
  INSERT INTO ZZ_GROUP_AUTHORITIES(GROUP_ID, AUTHORITY) 
  SELECT GROUP_ID
       , 'ROLE_USER' 
    FROM ZZ_GROUPS 
   WHERE GROUP_NAME='USERS'; 
  
  INSERT INTO ZZ_GROUP_AUTHORITIES(GROUP_ID, AUTHORITY) 
  SELECT GROUP_ID
       , 'ROLE_USER' 
    FROM ZZ_GROUPS 
   WHERE GROUP_NAME='ADMINISTRATORS'; 
  
  INSERT INTO ZZ_GROUP_AUTHORITIES(GROUP_ID, AUTHORITY) 
  SELECT GROUP_ID
       , 'ROLE_ADMIN' 
    FROM ZZ_GROUPS 
   WHERE GROUP_NAME='ADMINISTRATORS';   
   
  INSERT INTO ZZ_USERS(USER_NAME, USER_PW, USE_FLAG) 
  VALUES ('ADMIN','ADMIN',1);
  
  INSERT INTO ZZ_USERS(USER_NAME, USER_PW, USE_FLAG) 
  VALUES ('GUEST','GUEST',1);   
  
  INSERT INTO ZZ_GROUP_MEMBERS(GROUP_MEMBERS_ID, GROUP_ID, USER_NAME) 
  SELECT 1, GROUP_ID,'GUEST' 
    FROM ZZ_GROUPS 
   WHERE GROUP_NAME='USERS';
   
  INSERT INTO ZZ_GROUP_MEMBERS(GROUP_MEMBERS_ID, GROUP_ID, USER_NAME) 
  SELECT 2, GROUP_ID,'ADMIN' 
    FROM ZZ_GROUPS 
   WHERE GROUP_NAME='ADMINISTRATORS';  
  
  
  
  